Database port is expected to be an Integer with puppet 4
The default value uses a String, which clashes with the current
puppetlabs-postgres module and Puppet 4.
The error given is:
``` shell
Error: Could not retrieve catalog from remote server: Error 500 on
SERVER: Server Error: Evaluation Error: Error while evaluating a
Resource Statement, Postgresql::Server::Grant[database:GRANT puppetdb -
all - puppetdb]: parameter 'port' expects an Integer value, got String
at
/etc/puppetlabs/code/environments/production/modules/postgresql/manifests/server/database_grant.pp:10
on node node.domain
```