cron puppetdb-dlo-cleanup requires package
Fixes the following error

Error: /Stage[main]/Puppetdb::Server/Cron[puppetdb-dlo-cleanup]: Could not evaluate: Cannot write the puppetdb user's crontab: The user does not exist